
import React from 'react';
import { 
  LayoutDashboard, Users, BookOpen, Banknote, CalendarCheck, Settings, 
  PieChart, ShieldAlert, Building, Sprout, PiggyBank, Gavel, 
  Receipt, ClipboardCheck, HelpCircle, Bell, UserCog
} from 'lucide-react';

export const MENU_ITEMS = [
  { id: 'dashboard', label: { en: 'Dashboard', rw: 'Incamake' }, icon: <LayoutDashboard size={20} />, path: '/' },
  { id: 'groups', label: { en: 'Groups', rw: 'Amatsinda' }, icon: <Building size={20} />, path: '/groups' },
  { id: 'members', label: { en: 'Members', rw: 'Abanyamuryango' }, icon: <Users size={20} />, path: '/members' },
  { id: 'seasons', label: { en: 'Seasons / Cycles', rw: 'Igihembwe' }, icon: <Sprout size={20} />, path: '/seasons' },
  { id: 'contributions', label: { en: 'Contributions (Savings)', rw: 'Ubwizigame' }, icon: <PiggyBank size={20} />, path: '/contributions' },
  { id: 'loans', label: { en: 'Loans', rw: 'Inguzanyo' }, icon: <Banknote size={20} />, path: '/loans' },
  { id: 'fines', label: { en: 'Fines', rw: 'Amande' }, icon: <Gavel size={20} />, path: '/fines' },
  { id: 'expenses', label: { en: 'Expenses', rw: 'Amafaranga yasohotse' }, icon: <Receipt size={20} />, path: '/expenses' },
  { id: 'attendance', label: { en: 'Attendance', rw: 'Ubwitabire' }, icon: <ClipboardCheck size={20} />, path: '/attendance' },
  { id: 'reports', label: { en: 'Reports', rw: 'Raporo' }, icon: <PieChart size={20} />, path: '/reports' },
  { id: 'notifications', label: { en: 'Notifications', rw: 'Amatangazo' }, icon: <Bell size={20} />, path: '/notifications' },
  { id: 'users', label: { en: 'Users & Roles', rw: 'Abakoresha' }, icon: <UserCog size={20} />, path: '/users' },
  { id: 'settings', label: { en: 'Settings', rw: 'Igenamiterere' }, icon: <Settings size={20} />, path: '/settings' },
  { id: 'audit', label: { en: 'Audit Logs', rw: 'Ubugenzuzi' }, icon: <ShieldAlert size={20} />, path: '/audit' },
  { id: 'help', label: { en: 'Help / Support', rw: 'Ubufasha' }, icon: <HelpCircle size={20} />, path: '/help' },
];

export const EMAIL_CONFIG = {
  defaultFrom: "VJN System <notifications@amatsinda.vjn.org.rw>", 
  replyTo: "support@amatsinda.vjn.org.rw"
};

export const LABELS = {
  en: {
    // General
    appName: "VJN GSLA Management System",
    welcome: "Welcome back",
    currency: "RWF",
    loading: "Loading...",
    noData: "No records found.",
    date: "Date",
    amount: "Amount",
    description: "Description",
    type: "Type",
    actions: "Actions",
    status: "Status",
    search: "Search...",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    back: "Back",
    submit: "Submit",
    processing: "Processing...",
    void: "Void",
    history: "History",
    notes: "Notes",
    reason: "Reason",
    viewHistory: "View History",
    warning: "Warning",
    error: "Error",
    close: "Close",
    next: "Next",
    step: "Step",
    of: "of",
    send: "Send",
    categories: "Categories",
    viewDetails: "View Details",
    quickTips: "Quick Tips",
    
    // Auth & Greetings
    goodMorning: "Good Morning",
    goodAfternoon: "Good Afternoon",
    goodEvening: "Good Evening",
    signIn: "Sign In",
    emailAddr: "Email Address",
    password: "Password",
    securePortal: "Secure Access Portal",
    unauthMsg: "Unauthorized access is prohibited. All activities are logged.",
    verifyIdentity: "Verify Identity",
    recoverAccess: "Recover Access",
    enterCode: "Enter the secure code sent to your inbox",
    enterEmailRecover: "Enter your email to receive a recovery link",
    sendLink: "Send Link",
    verifyCode: "Verify Code",
    invalidCode: "Invalid code",
    
    // Notifications & Messaging
    composeBroadcast: "Compose Broadcast",
    sendMessage: "Send Message",
    sendEmail: "Send Email",
    channel: "Channel",
    recipients: "Recipients",
    allMembers: "All Members",
    subject: "Subject",
    message: "Message",
    msgSentSuccess: "Message sent successfully!",
    msgFailed: "Failed to send message.",
    emailSentSim: "Email Simulation: Sent to",
    
    // Profile
    profile: "User Profile",
    personalInfo: "Personal Information",
    security: "Security",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    updateProfile: "Update Profile",
    updateSuccess: "Profile updated successfully",
    emailFixed: "Email cannot be changed.",
    secureAccount: "Secure your account with an extra layer of protection.",
    activeAccount: "Active on your account.",
    
    // Roles & Status & Enums
    superAdmin: "Super Admin",
    admin: "Admin",
    groupLeader: "Group Leader",
    memberUser: "Member",
    active: "Active",
    suspended: "Suspended",
    closed: "Closed",
    exited: "Exited",
    all: "All",
    allStatus: "All Status",
    weekly: "Weekly",
    biweekly: "Biweekly",
    monthly: "Monthly",
    regular: "Regular",
    special: "Special",
    emergency: "Emergency",
    activeUser: "Active User",
    
    // Stepper
    stepAttendance: "Attendance",
    stepSavings: "Savings",
    stepLoans: "Loans",
    stepSummary: "Summary",

    // Dashboard
    dashboard: "Dashboard",
    totalGroups: "Total Groups",
    totalSavings: "Total Savings",
    loansActive: "Active Loans",
    outstandingLoans: "Outstanding Balance",
    unpaidLoans: "Unpaid Loans",
    revenue: "Est. Revenue",
    members: "Members",
    cashBalance: "Cash Balance",
    overdue: "Overdue Loans",
    unpaidFinesTotal: "Unpaid Fines",
    lateLoans: "Late Loans",
    quickActions: "Quick Actions",
    financialTrends: "Financial Trends",
    healthIndicators: "Group Health Indicators",
    repaymentRate: "Repayment Rate",
    attendanceRate: "Attendance Rate",
    upcomingSchedule: "Upcoming Schedule",
    nextMeeting: "Next Meeting",
    loansDueSoon: "Loans Due Soon",
    assetAllocation: "Asset Allocation",
    activeSeasons: "Active Season",
    shareValue: "Share Value",
    currentShareValue: "Current Share Value",
    initialValue: "Initial Value",
    valueGrowth: "Growth",
    sharesCollected: "Shares Collected",
    recordContribution: "Record Contribution",
    recordRepayment: "Record Repayment",
    recordNewFine: "Record New Fine",
    attendance: "Attendance",
    expenses: "Expenses",
    lastAttendance: "Last Meeting Attendance",
    repeatedAbsence: "Repeated Absence",
    contributionsSeason: "Contributions (Season)",
    contributionsMonth: "Contributions (Month)",
    expensesSeason: "Expenses (Season)",
    mySavings: "My Total Savings",
    myLoans: "My Loan Balance",
    myAttendance: "My Attendance",
    aggregatePortfolio: "You are viewing the Aggregate Portfolio",
    systemStatus: "System Status",
    financialHealthGood: "Financial health is good.",
    avgUnitValue: "Avg. Unit Value",
    thisMonth: "This Month",
    presence: "Presence",

    // Groups & Forms
    groupsManagement: "Groups Management",
    manageGroupsDesc: "Manage GSLA governance and settings",
    newGroup: "New Group",
    manageProfile: "Manage Profile",
    locationDetails: "Location Details",
    currentStatus: "Current Status",
    governanceStructure: "Governance Structure",
    financialConfiguration: "Financial Configuration",
    auditTrail: "Audit Trail",
    modifyGroup: "Modify Group",
    createGroupTitle: "Create New GSLA Group",
    identification: "Identification",
    financialRules: "Financial Rules",
    groupName: "Group Name",
    district: "District",
    sector: "Sector",
    cell: "Cell",
    village: "Village",
    gpsLocation: "GPS Location",
    updateGps: "Update GPS",
    getGps: "Get GPS",
    coordinatesCaptured: "Coordinates captured",
    coordinatesNotCaptured: "Coordinates not captured",
    meetingFreq: "Meeting Freq.",
    loanMultiplier: "Loan Multiplier",
    constitution: "Constitution / Bylaws",
    fileAttached: "File Attached",
    noFileSelected: "No file selected",
    uploadInstruction: "Upload the signed group constitution or internal rules for digital reference.",
    president: "President",
    secretary: "Secretary",
    accountant: "Accountant",
    selectMember: "Select Member",
    
    // Members
    addMember: "Add Member",
    editMember: "Edit Member",
    removeMember: "Remove Member",
    memberSearchPlaceholder: "Search (Name, Phone, ID)",
    loanBalance: "Loan Balance",
    fullName: "Full Name",
    nationalId: "National ID",
    phoneNumber: "Phone Number",
    role: "Role",
    importCsv: "Import CSV",
    csvFormat: "Format: Name, NationalID, Phone, Role",
    memberPhoto: "Member Photo",
    uploadPhotoDesc: "Upload a clear headshot for identification.",
    confirmRemoveMember: "Are you sure you want to remove this member?",
    archiveWarning: "If they have financial history, they will be archived instead of deleted.",
    template: "Template",
    
    // Loans
    loanManagement: "Loan Management",
    applyLoan: "Apply for Loan",
    newLoanApp: "New Loan Application",
    loanEstimator: "Loan Estimator",
    penaltyTool: "Penalty Tool",
    penaltyManager: "Penalty Manager",
    latePenalties: "Late Penalties",
    pendingApproval: "Pending Approval",
    approve: "Approve",
    reject: "Reject",
    portfolio: "Portfolio",
    monthlyPayment: "Monthly Payment",
    totalInterest: "Total Interest",
    totalRepayment: "Total Repayment",
    hidePenalty: "Hide Penalty",
    hideCalc: "Hide Calc",
    penaltyType: "Penalty Type",
    percentage: "Percentage",
    fixedAmount: "Fixed Amount",
    percentageRate: "Percentage Rate",
    applyPenalties: "Apply Penalties",
    simpleInterest: "Simple Interest",
    perMonth: "Per month",
    durationMonths: "Duration (Months)",
    months: "Months",
    formulaNote: "Formula: Principal + (Principal × Rate × Months). Actual amounts may vary.",
    maxEligible: "Max Eligible Loan",
    exceedsLimit: "Exceeds maximum limit",
    repaymentFor: "Repaying loan for",
    currentBalance: "Current Balance",
    repaymentAmount: "Repayment Amount",
    clearsLoan: "This payment will clear the loan.",
    purpose: "Purpose",
    interestBreakdown: "Interest Breakdown",
    feesApplied: "Fees Applied Successfully",
    principal: "Principal",
    repaid: "Repaid",
    balance: "Balance",
    progress: "Progress",
    dueDate: "Due Date",
    
    // Meeting Mode
    startMeeting: "Start Meeting Recording",
    meetingDesc: "Record attendance and transactions for the group meeting.",
    saveMeeting: "Save Meeting Data",
    finesCollected: "Fines Collected",
    loanRepayments: "Loan Repayments",
    present: "Present",
    absent: "Absent",
    late: "Late",
    meetingSaved: "Meeting Saved!",
    meetingSavedDesc: "All transactions have been recorded successfully.",
    startNewMeeting: "Start New Meeting",
    markAttendance: "Mark Attendance",
    allPresent: "All Present",
    reset: "Reset",
    onlyPresent: "Only showing present members",
    collectSavings: "Collect Savings",
    loansFines: "Loans & Fines",
    meetingSummary: "Meeting Summary",
    repayments: "Repayments",
    totalCashIn: "Total Cash In",
    reviewTx: "Review Transactions",
    saveDesc: "You are about to save transaction records.",
    
    // Contributions
    sharesLedger: "Shares Ledger",
    strictRecording: "Strict financial recording",
    newContribution: "New Contribution",
    shareCount: "Share Count",
    solidarity: "Solidarity",
    auditWarning: "All changes are audited. You must provide a valid reason.",
    voidConfirm: "Are you sure you want to void this transaction?",
    shareCapitalInv: "Share Capital (Investment)",
    socialFundIns: "Social Fund (Insurance)",
    refundableEnd: "Refundable at cycle end",
    nonRefundable: "Non-refundable pot",
    insuranceContrib: "Insurance Contribution",
    
    // Fines
    fines: "Fines",
    outstandingFines: "Outstanding Fines",
    collectedSeason: "Collected (Season)",
    manageCategories: "Manage Categories",
    payFine: "Pay Fine",
    recordFine: "Record Fine",
    categoryName: "Category Name",
    addNewCategory: "Add New Category",
    backToList: "Back to List",
    
    // Expenses
    totalExpenses: "Total Expenses (Season)",
    addExpense: "Add Expense",
    expenseManagement: "Expense Management",
    availableCash: "Available Cash",
    insufficientFunds: "Insufficient funds in cash balance.",
    expenseCategory: "Expense Category",
    approvedBy: "Approved By",
    recordedBy: "Recorded By",
    trackAudit: "Track and audit group expenditures",
    balanceAuditWarning: "Warning: Changing expense details will affect the cash balance audit.",
    whyChange: "Why is this being changed?",
    
    // Attendance
    attendanceManagement: "Attendance Management",
    scheduleNewMeeting: "Schedule New Meeting",
    regularWeekly: "Regular Weekly",
    specialEvent: "Special Event",
    emergency: "Emergency",
    recordingAttendance: "Recording Attendance",
    correctAttendance: "Correct Attendance",
    
    // Seasons
    cycleManagement: "Cycle Management",
    currentActive: "Current Season Active",
    startedOn: "Started on",
    interestRate: "Interest Rate",
    openForTx: "Open for Transactions",
    closeSeason: "Close Season",
    shareOutReport: "Share-out Report",
    shareOutDesc: "Calculating share-out values requires closing all outstanding loans and reconciling fines.",
    viewReport: "View Final Report",
    simulateShareOut: "Simulate Share-out",
    viewPrevious: "View previous seasons",
    noActiveSeason: "No active season found for this group.",
    startNewSeason: "Start New Season",
    calculating: "Calculating financial positions...",
    shareOutPreview: "Share-Out Preview",
    simulated: "Simulated",
    shareEligible: "Share-Eligible Income",
    excludedFunds: "Excluded Funds (Non-Share)",
    reservedFundsMsg: "These funds are strictly reserved for welfare and are NOT included in the share-out calculation.",
    outstandingWarning: "Warning: Outstanding Loans Detected",
    finalizeSeason: "Finalize & Close Season",
    confirmSeasonClose: "Finalize Share-Out & Close Season?",
    irreversibleAction: "This action is irreversible.",
    
    // Seasons Wizard
    wizStepHealth: "Health Check",
    wizStepFinancials: "Financials",
    wizStepPayouts: "Payouts",
    wizStepConfirm: "Confirm",
    wizStartTimeline: "Timeline",
    wizStartSavings: "Savings",
    wizStartLoans: "Loans",
    wizStartReview: "Review",
    closeWizardTitle: "Close Season Wizard",
    calculatingPositions: "Calculating final positions for",
    outstandingCheck: "Outstanding Loans Check",
    loansWarningTitle: "Warning: Unpaid Loans Detected",
    loansWarningDesc: "There is {amount} in outstanding loans. Closing the season now means this amount is counted as an asset (Net Worth) but you do not have the cash to pay it out.",
    recoverRecommendation: "Recommendation: Recover all loans before closing.",
    loansCleared: "All loans cleared. Good to go!",
    finesReconciliation: "Fines Reconciliation",
    finesDesc: "Ensure all fines are collected or written off.",
    totalShareContrib: "Total Share Contributions",
    totalProfits: "Total Profits (Interest + Fines)",
    expensesLosses: "Expenses & Losses",
    netDistributable: "Net Distributable",
    finalShareValue: "Final Share Value",
    memberPayoutSchedule: "Member Payout Schedule",
    printReport: "Print Report",
    confirmCloseTitle: "Are you absolutely sure?",
    confirmCloseDesc: "This action will archive the current season and lock all financial records. Make sure all cash has been distributed to members according to the Payout Schedule.",
    shareValueFinalized: "Share Value finalized at",
    membersCalculated: "members calculated",
    historyPreserved: "Cycle history preserved",
    confirmPayouts: "I confirm that all payouts are complete.",
    
    // Start Season Wizard
    seasonTimeline: "Season Timeline",
    timelineDesc: "Define the operating period for this cycle.",
    seasonName: "Season Name",
    startDate: "Start Date",
    expectedEnd: "Expected End",
    contributionRules: "Contribution Rules",
    contributionDesc: "Set the value of shares and contribution limits.",
    sharePrice: "Share Price",
    sharePriceDesc: "The value of a single stamp/share.",
    minShares: "Min Shares",
    maxShares: "Max Shares",
    socialFundFee: "Social Fund",
    loanConfig: "Loan Configuration",
    loanConfigDesc: "Define interest rates and credit limits.",
    interestRatePercent: "Interest Rate (%)",
    loanLimitMultiplier: "Loan Limit (x)",
    multiplierDesc: "Multiplier of savings",
    latePenalty: "Late Payment Penalty",
    penaltyPercent: "Percentage %",
    penaltyFixed: "Fixed Amount",
    finalCheck: "Final Check",
    finalCheckDesc: "Starting a new season creates an immutable financial ledger. Ensure all members agree to these rules.",
    confirmSettings: "I confirm these settings are correct.",
    launchSeason: "Launch Season",

    // Reports
    reports: "Reports",
    reportTypes: "Report Types",
    financial: "Financial",
    operational: "Operational",
    endOfCycle: "End-ofCycle",
    exportCsv: "Export CSV",
    printPdf: "Print PDF",
    generated: "Generated",
    netPosition: "Net Position",
    inflowsBreakdown: "Inflows Breakdown",
    outflowsBreakdown: "Outflows Breakdown",
    projectedReport: "PROJECTED REPORT (SIMULATION)",
    finalReport: "FINAL CLOSED REPORT",
    totalCash: "Total Cash",
    socialFund: "Social Fund",
    loansAssets: "Loans Assets",
    netWorth: "Net Worth",
    valuePerShare: "Value / Share",
    invested: "Invested",
    profit: "Profit",
    totalPayout: "Total Payout",
    confidential: "Confidential Financial Report",
    totalInflow: "Total Inflow",
    totalOutflow: "Total Outflow",
    memberFinancialSummary: "Member Financial Summary",
    topSavers: "Top 10 Savers",
    portfolioHealth: "Portfolio Health (Count)",
    flowComparison: "Flow Comparison",
    
    // Settings & Users
    settingsTitle: "Configuration",
    language: "System Language",
    languageDesc: "Choose between English and Kinyarwanda",
    usersRoles: "Users & Roles",
    usersRolesDesc: "Manage admin access and group leaders",
    manageUsers: "Manage Users",
    dataBackup: "Data & Backup",
    dataBackupDesc: "Export all system data for offline storage",
    exportJson: "Export JSON",
    resetDb: "Reset Database",
    resetDbDesc: "Clear all local data and reset to initial state",
    systemMaintenance: "System Maintenance",
    clearCache: "Clear Local Cache",
    clearCacheDesc: "Fix display issues by clearing local storage. Requires re-login.",
    verifyHealth: "Verify Health",
    healthCheckDesc: "Check database connection and system status.",
    systemUsers: "System Users & Roles",
    manageAccess: "Manage access control and permissions",
    addUser: "Add User",
    totalUsers: "Total Users",
    admins: "Admins",
    groupLeaders: "Group Leaders",
    lockedDisabled: "Locked/Disabled",
    searchUsers: "Search users...",
    scope: "Scope",
    lastLogin: "Last Login",
    createUser: "Create User",
    editUser: "Edit User",
    editUserTitle: "Edit User",
    saveUser: "Save User",
    removeUser: "Remove User",
    initialPassword: "Initial Password",
    assignedGroup: "Assigned Group",
    never: "Never",
    global: "Global / None",
    enableAi: "Enable Help Assistant",
    rlsConfig: "Database & Security (RLS)",
    copySql: "Copy SQL",
    runSqlWarning: "Important: Run this SQL in your Supabase Dashboard to apply security rules.",
    clearCacheBtn: "Clear Cache",
    resetLocal: "Clear & Logout",
    confirmRemoveUser: "Are you sure you want to delete this user? This action cannot be undone.",
    
    // Audit & Help
    auditLogs: "Audit Logs",
    userGuide: "User Guide",
    contactSupport: "Contact Support",
    timestamp: "Timestamp",
    userLog: "User",
    actionLog: "Action",
    detailsLog: "Details",
    
    // Layout
    notifications: "Notifications",
    markAllRead: "Mark all read",
    noNotifications: "No notifications",
    markRead: "Mark Read",
    logout: "Logout",
    groupSelector: "Group:",
    switchLanguage: "Switch Language",
    helpAssistant: "Help Assistant",
    askMeAnything: "Ask me how to use the system..."
  },
  rw: {
    // General
    appName: "Sisitemu ya VJN GSLA",
    welcome: "Murakaza neza",
    currency: "RWF",
    loading: "Birigutunganywa...",
    noData: "Nta makuru ahari.",
    date: "Itariki",
    amount: "Amafaranga",
    description: "Ubusobanuro",
    type: "Ubwoko",
    actions: "Ibikorwa",
    status: "Imiterere",
    search: "Shakisha...",
    cancel: "Kureka",
    save: "Bika",
    edit: "Hindura",
    delete: "Siba",
    confirm: "Emeza",
    back: "Subira inyuma",
    submit: "Ohereza",
    processing: "Birigukorwa...",
    void: "Tesha agaciro",
    history: "Amateka",
    notes: "Inyandiko",
    reason: "Impamvu",
    viewHistory: "Reba Amateka",
    warning: "Icyitonderwa",
    error: "Ikosa",
    close: "Funga",
    next: "Komeza",
    step: "Intambwe",
    of: "ya",
    verifyIdentity: "Kugenzura Umwirondoro",
    recoverAccess: "Kugarura Konti",
    enterCode: "Andika umubare w'ibanga wohererejwe",
    enterEmailRecover: "Andika imeyili yawe tubone uko tugufasha",
    sendLink: "Ohereza",
    verifyCode: "Emeza",
    invalidCode: "Umubare utari wo",
    send: "Ohereza",
    categories: "Ubwoko",
    viewDetails: "Reba Birambuye",
    quickTips: "Inama z'Ingenzi",

    // Notifications & Messaging
    composeBroadcast: "Andika Itangazo",
    sendMessage: "Ohereza Ubutumwa",
    sendEmail: "Ohereza Imeyili",
    channel: "Uburyo",
    recipients: "Abo bigenewe",
    allMembers: "Abanyamuryango Bose",
    subject: "Impamvu",
    message: "Ubutumwa",
    msgSentSuccess: "Ubutumwa bwoherejwe neza!",
    msgFailed: "Ntibyakunze kohereza ubutumwa.",
    emailSentSim: "Imeyili yoherejwe kuri",

    // Profile
    profile: "Imyirondoro yanjye",
    personalInfo: "Amakuru yanjye",
    security: "Umutekano",
    changePassword: "Hindura ijambo ry'ibanga",
    currentPassword: "Ijambo ry'ibanga risanzwe",
    newPassword: "Ijambo ry'ibanga rishya",
    confirmPassword: "Emeza ijambo ry'ibanga",
    updateProfile: "Vugurura Imyirondoro",
    updateSuccess: "Imyirondoro yavuguruwe",
    emailFixed: "Imeyili ntishobora guhindurwa.",
    secureAccount: "Ongera umutekano wa konti yawe.",
    activeAccount: "Birakora kuri konti yawe.",

    // Roles & Status & Enums
    superAdmin: "Umuhuzabikorwa Mukuru",
    admin: "Ushinzwe Porogaramu",
    groupLeader: "Umuyobozi w'Itsinda",
    memberUser: "Umunyamuryango",
    active: "Gikora",
    suspended: "Hagaritswe",
    closed: "Funze",
    exited: "Sezeye",
    all: "Byose",
    allStatus: "Imiterere Yose",
    weekly: "Rimwe mu Cyumweru",
    biweekly: "Kabiri mu Cyumweru",
    monthly: "Rimwe mu Kwezi",
    regular: "Bisanzwe",
    special: "Idasanzwe",
    emergency: "Iyihutirwa",
    activeUser: "Arakora",

    // Stepper
    stepAttendance: "Ubwitabire",
    stepSavings: "Ubwizigame",
    stepLoans: "Inguzanyo",
    stepSummary: "Incamake",

    // Dashboard
    dashboard: "Incamake",
    totalGroups: "Amatsinda Yose",
    totalSavings: "Ubwizigame Bwose",
    loansActive: "Inguzanyo Zatanzwe",
    outstandingLoans: "Ideni Risigaye",
    unpaidLoans: "Inguzanyo Zitarishyuwe",
    revenue: "Inyungu (Igereranyo)",
    members: "Abanyamuryango",
    cashBalance: "Amafaranga Ariho",
    overdue: "Ibirarane",
    unpaidFinesTotal: "Amande Atarishyuwe",
    lateLoans: "Inguzanyo Zakererewe",
    quickActions: "Ibikorwa Byihuse",
    financialTrends: "Imigendekere y'Imari",
    healthIndicators: "Ibipimo by'Ubuzima bw'Itsinda",
    repaymentRate: "Igipimo cyo Kwishyura",
    attendanceRate: "Igipimo cy'Ubwitabire",
    upcomingSchedule: "Gahunda iri imbere",
    nextMeeting: "Inama Itaha",
    loansDueSoon: "Inguzanyo zenda kwishyurwa",
    assetAllocation: "Imiterere y'Umutungo",
    activeSeasons: "Igihembwe Gihari",
    shareValue: "Agaciro k'Umugabane",
    currentShareValue: "Agaciro k'Umugabane (Ubu)",
    initialValue: "Agaciro k'Itangiriro",
    valueGrowth: "Inyongera",
    sharesCollected: "Imigabane Yakusanyijwe",
    recordContribution: "Andika Ubwizigame",
    recordRepayment: "Andika Ubwishyu",
    recordNewFine: "Andika Amande Mashya",
    attendance: "Ubwitabire",
    expenses: "Amafaranga Yasohotse",
    lastAttendance: "Ubwitabire bw'Inama Iheruka",
    repeatedAbsence: "Abasiba Kenshi",
    contributionsSeason: "Ubwizigame (Igihembwe)",
    contributionsMonth: "Ubwizigame (Ukwezi)",
    expensesSeason: "Ayasohotse (Igihembwe)",
    mySavings: "Ubwizigame Bwanjye",
    myLoans: "Ideni Nsigaje",
    myAttendance: "Ubwitabire Bwanjye",
    aggregatePortfolio: "Incamake y'Amatsinda Yose",
    systemStatus: "Imiterere ya Sisitemu",
    financialHealthGood: "Ubuzima bw'imari bumeze neza.",
    avgUnitValue: "Agaciro k'impuzandengo",
    thisMonth: "Kuri Uku Kwezi",
    presence: "Kwitabira",

    // Groups & Forms
    groupsManagement: "Gucunga Amatsinda",
    manageGroupsDesc: "Gena imikorere n'amategeko y'amatsinda",
    newGroup: "Itsinda Rishya",
    manageProfile: "Gucunga Itsinda",
    locationDetails: "Amakuru y'Aho riherereye",
    currentStatus: "Imiterere y'Ubu",
    governanceStructure: "Imiterere y'Ubuyobozi",
    financialConfiguration: "Igenamiterere ry'Imari",
    auditTrail: "Inzira y'Ubugenzuzi",
    modifyGroup: "Hindura Itsinda",
    createGroupTitle: "Kurema Itsinda Rishya rya GSLA",
    identification: "Umwirondoro",
    financialRules: "Amategeko y'Imari",
    groupName: "Izina ry'Itsinda",
    district: "Akarere",
    sector: "Umurenge",
    cell: "Akagari",
    village: "Umudugudu",
    gpsLocation: "Ahantu (GPS)",
    updateGps: "Vugurura GPS",
    getGps: "Fata GPS",
    coordinatesCaptured: "Imibare ya GPS yafashwe",
    coordinatesNotCaptured: "Nta GPS yafashwe",
    meetingFreq: "Inshuro z'Inama",
    loanMultiplier: "Inkubo y'Inguzanyo",
    constitution: "Amategeko Ngengamikorere",
    fileAttached: "Dosiye yometseho",
    noFileSelected: "Nta dosiye yahisemo",
    uploadInstruction: "Shyiraho amategeko yashyizweho umukono cyangwa izindi nyandiko.",
    president: "Perezida",
    secretary: "Umunyamabanga",
    accountant: "Umucungamari",
    selectMember: "Hitamo Umunyamuryango",

    // Members
    addMember: "Ongeramo Umunyamuryango",
    editMember: "Hindura Umunyamuryango",
    removeMember: "Kuramo Umunyamuryango",
    memberSearchPlaceholder: "Shakisha (Izina, Telefoni, ID)",
    loanBalance: "Ideni Risigaye",
    fullName: "Amazina Yombi",
    nationalId: "Indangamuntu",
    phoneNumber: "Telefoni",
    role: "Inshingano",
    importCsv: "Shyiramo CSV",
    csvFormat: "Imiterere: Izina, Indangamuntu, Telefoni, Inshingano",
    memberPhoto: "Ifoto",
    uploadPhotoDesc: "Shyiraho ifoto igaragara neza.",
    confirmRemoveMember: "Ese koko urashaka gukuramo uyu munyamuryango?",
    archiveWarning: "Niba afite amateka y'imari, azabikwa (archive) aho gusibwa burundu.",
    template: "Urugero",
    
    // Loans
    loanManagement: "Gucunga Inguzanyo",
    applyLoan: "Saba Inguzanyo",
    newLoanApp: "Kwandika Inguzanyo Nshya",
    loanEstimator: "Ibalura ry'Inguzanyo",
    penaltyTool: "Ibihano",
    penaltyManager: "Gucunga Ibihano",
    latePenalties: "Ibihano by'Ubukererewe",
    pendingApproval: "Zitegereje Kwemezwa",
    approve: "Emeza",
    reject: "Hakana",
    portfolio: "Inguzanyo Zose",
    monthlyPayment: "Yishyurwa ku Kwezi",
    totalInterest: "Inyungu Yose",
    totalRepayment: "Ayishyurwa Yose",
    hidePenalty: "Hisha Ibihano",
    hideCalc: "Hisha Ibalura",
    penaltyType: "Ubwoko bw'Igihano",
    percentage: "Ijanisha",
    fixedAmount: "Amafaranga Azwi",
    percentageRate: "Ijanisha (%)",
    applyPenalties: "Emeza Ibihano",
    simpleInterest: "Inyungu Isanzwe",
    perMonth: "Ku kwezi",
    durationMonths: "Igihe (Amezi)",
    months: "Amezi",
    formulaNote: "Ibalura: Inguzanyo + (Inguzanyo x Inyungu x Amezi).",
    maxEligible: "Inguzanyo Ntarengwa yemewe",
    exceedsLimit: "Irenze urugero rwemejwe",
    repaymentFor: "Kwishyurira",
    currentBalance: "Ideni Risigaye",
    repaymentAmount: "Ayishyurwa",
    clearsLoan: "Ubu bwishyu burasoza ideni.",
    purpose: "Impamvu",
    interestBreakdown: "Imiterere y'Inyungu",
    feesApplied: "Ibihano byatanzwe neza",
    principal: "Igishoro",
    repaid: "Ayishyuwe",
    balance: "Asigaye",
    progress: "Ibikomeje",
    dueDate: "Igihe Ntarengwa",

    // Meeting Mode
    startMeeting: "Tangira Kwandika Inama",
    meetingDesc: "Andika ubwitabire n'ibikorwa by'amafaranga by'inama.",
    saveMeeting: "Bika Amakuru y'Inama",
    finesCollected: "Amande Yakusanyijwe",
    loanRepayments: "Kwishura Inguzanyo",
    present: "Yitabiriye",
    absent: "Yasibye",
    late: "Yakererewe",
    meetingSaved: "Inama yabitswe!",
    meetingSavedDesc: "Ibyakozwe byose byabitswe neza.",
    startNewMeeting: "Tangira Inama Nshya",
    markAttendance: "Kwandika Abitabiriye",
    allPresent: "Bose Bahari",
    reset: "Subiramo",
    onlyPresent: "Herekana gusa abahari",
    collectSavings: "Kwakira Ubwizigame",
    loansFines: "Inguzanyo & Amande",
    meetingSummary: "Incamake y'Inama",
    repayments: "Ubwishyu",
    totalCashIn: "Amafaranga Yose Yinjiye",
    reviewTx: "Reba Ibyakozwe",
    saveDesc: "Ugiye kubika inyandiko z'imari.",

    // Contributions
    sharesLedger: "Igitabo cy'Imigabane",
    strictRecording: "Kwandika iby'imari byitondewe",
    newContribution: "Ubwizigame Bushya",
    shareCount: "Umubare w'Imigabane",
    solidarity: "Ingoboka",
    auditWarning: "Impinduka zose ziragenzurwa. Ugomba gutanga impamvu yumvikana.",
    voidConfirm: "Ese uremera gutesha agaciro ubu bwizigame?",
    shareCapitalInv: "Imigabane Shingiro (Ishoramari)",
    socialFundIns: "Isanduku y'Ingoboka (Ubwishingizi)",
    refundableEnd: "Yishyurwa ku musozo",
    nonRefundable: "Ntigaruzwa",
    insuranceContrib: "Umusanzu w'Ubwishingizi",

    // Fines
    fines: "Amande",
    outstandingFines: "Amande Atarishyuwe",
    collectedSeason: "Ayakusanyijwe (Igihembwe)",
    manageCategories: "Gucunga Ibyiciro",
    payFine: "Ishyura Amande",
    recordFine: "Andika Amande",
    categoryName: "Izina ry'Icyiciro",
    addNewCategory: "Ongeramo Icyiciro Gishya",
    backToList: "Subira ku Rutonde",

    // Expenses
    totalExpenses: "Amafaranga yose yasohotse (Igihembwe)",
    addExpense: "Ongeramo Ayasohotse",
    expenseManagement: "Gucunga Ayasohotse",
    availableCash: "Amafaranga Ariho",
    insufficientFunds: "Amafaranga ntabwo ahagije.",
    expenseCategory: "Icyiciro cy'Isoko",
    approvedBy: "Yemejwe na",
    recordedBy: "Yanditswe na",
    trackAudit: "Gukurikirana no kugenzura ayasohotse",
    balanceAuditWarning: "Icyitonderwa: Guhindura ibi bizagira ingaruka kuibarura ry'amafaranga ariho.",
    whyChange: "Kuki ugiye kubihindura?",

    // Attendance
    attendanceManagement: "Gucunga Ubwitabire",
    scheduleNewMeeting: "Tegura Inama Nshya",
    regularWeekly: "Isanzwe ya Buri Cyumweru",
    specialEvent: "Igikorwa Cyihariye",
    emergency: "Iyihutirwa",
    recordingAttendance: "Kwandika Ubwitabire",
    correctAttendance: "Gukosora Ubwitabire",

    // Seasons
    cycleManagement: "Gucunga Ibihembwe",
    currentActive: "Igihembwe Gihari",
    startedOn: "Cyatangiye kuwa",
    interestRate: "Inyungu",
    openForTx: "Kirafunguye",
    closeSeason: "Funga Igihembwe",
    shareOutReport: "Raporo yo Kugabana",
    shareOutDesc: "Kubara imigabane bisaba kwishura inguzanyo zose no gukemura amande.",
    viewReport: "Reba Raporo ya Nyuma",
    simulateShareOut: "Gereranya Kugabana",
    viewPrevious: "Reba ibihembwe byashize",
    noActiveSeason: "Nta gihembwe gihari muri iri tsinda.",
    startNewSeason: "Tangira Igihembwe Gishya",
    calculating: "Birigukorwa...",
    shareOutPreview: "Incamake yo Kugabana",
    simulated: "Byagereranyijwe",
    shareEligible: "Ibyemerewe Kugabanywa",
    excludedFunds: "Ibisigaye mu Kigega",
    reservedFundsMsg: "Aya mafaranga agenewe imibereho myiza kandi NTABWO abarwa mu kugabana.",
    outstandingWarning: "Icyitonderwa: Hari inguzanyo zitarishyurwa",
    finalizeSeason: "Gusoza Igihembwe Burundu",
    confirmSeasonClose: "Emeza Gusoza Igihembwe",
    irreversibleAction: "Iki gikorwa ntikigarurwa.",

    // Seasons Wizard
    wizStepHealth: "Kugenzura",
    wizStepFinancials: "Imari",
    wizStepPayouts: "Kugabana",
    wizStepConfirm: "Emeza",
    wizStartTimeline: "Igihe",
    wizStartSavings: "Ubwizigame",
    wizStartLoans: "Inguzanyo",
    wizStartReview: "Reba",
    closeWizardTitle: "Gusoza Igihembwe",
    calculatingPositions: "Kubara imibare ya nyuma ya",
    outstandingCheck: "Kugenzura Inguzanyo",
    loansWarningTitle: "Icyitonderwa: Hari inguzanyo zitarishyurwa",
    loansWarningDesc: "Hari {amount} z'inguzanyo zitarishyurwa. Gusoza ubu bivuze ko zibarwa nk'umutungo kandi nta mafaranga ahari.",
    recoverRecommendation: "Inama: Ishyuza inguzanyo zose mbere yo gusoza.",
    loansCleared: "Nta nguzanyo zirebwa. Byose ni byiza!",
    finesReconciliation: "Kugenzura Amande",
    finesDesc: "Reba ko amande yose yishyuwe cyangwa yakuweho.",
    totalShareContrib: "Imigabane Yose",
    totalProfits: "Inyungu (Inyungu + Amande)",
    expensesLosses: "Ayasohotse & Igihombo",
    netDistributable: "Ayagabanywa",
    finalShareValue: "Agaciro k'Umugabane (Nyuma)",
    memberPayoutSchedule: "Gahunda yo Kwishyura",
    printReport: "Sohora Raporo",
    confirmCloseTitle: "Ese urabyemeza neza?",
    confirmCloseDesc: "Ibi bizabika igihembwe kandi bifunge inyandiko z'imari. Reba ko amafaranga yose yatanzwe.",
    shareValueFinalized: "Agaciro k'umugabane: ",
    membersCalculated: "abanyamuryango babaruwe",
    historyPreserved: "Amateka y'igihembwe abitswe",
    confirmPayouts: "Ndemeza ko amafaranga yose yatanzwe.",

    // Start Season Wizard
    seasonTimeline: "Ingengabihe y'Igihembwe",
    timelineDesc: "Gena igihe cy'imikorere.",
    seasonName: "Izina ry'Igihembwe",
    startDate: "Itariki yo Gutangira",
    expectedEnd: "Itariki yo Gusoza (Iteganyijwe)",
    contributionRules: "Amategeko y'Ubwizigame",
    contributionDesc: "Gena agaciro k'imigabane n'imipaka.",
    sharePrice: "Igiciro cy'Umugabane",
    sharePriceDesc: "Agaciro k'umugabane umwe.",
    minShares: "Imigabane Nto",
    maxShares: "Imigabane Nini",
    socialFundFee: "Ingoboka",
    loanConfig: "Igenamiterere ry'Inguzanyo",
    loanConfigDesc: "Gena inyungu n'inguzanyo ntarengwa.",
    interestRatePercent: "Inyungu (%)",
    loanLimitMultiplier: "Inguzanyo Ntarengwa (x)",
    multiplierDesc: "Inkubo y'ubwizigame",
    latePenalty: "Ibihano by'Ubukererewe",
    penaltyPercent: "Ijanisha %",
    penaltyFixed: "Amafaranga Azwi",
    finalCheck: "Igenzura rya Nyuma",
    finalCheckDesc: "Gutangira igihembwe bitangira ibaruramari rishya. Reba ko abanyamuryango bose babyemera.",
    confirmSettings: "Ndemeza ko ibi bimeze neza.",
    launchSeason: "Tangiza Igihembwe",

    // Reports
    reports: "Raporo",
    reportTypes: "Ubwoko bwa Raporo",
    financial: "Imari",
    operational: "Ibikorwa",
    endOfCycle: "Gusoza Igihembwe",
    exportCsv: "Kurura CSV",
    printPdf: "Sohora PDF",
    generated: "Yakozwe",
    netPosition: "Imiterere Rusange",
    inflowsBreakdown: "Aho Amafaranga Yavuye",
    outflowsBreakdown: "Aho Amafaranga Yagiye",
    projectedReport: "RAPORO Y'IGERERANYA",
    finalReport: "RAPORO YA NYUMA",
    totalCash: "Amafaranga Ariho",
    socialFund: "Isanduku y'Ingoboka",
    loansAssets: "Inguzanyo (Umutungo)",
    netWorth: "Umutungo Rusange",
    valuePerShare: "Agaciro k'Umugabane",
    invested: "Yashowe",
    profit: "Inyungu",
    totalPayout: "Ayishyurwa Yose",
    confidential: "Raporo y'Ibanga - Ntigasakazwe",
    totalInflow: "Ayinjiye Yose",
    totalOutflow: "Ayasohotse Yose",
    memberFinancialSummary: "Incamake y'Imari y'Abanyamuryango",
    topSavers: "Abazigamye Cyane (10)",
    portfolioHealth: "Imiterere y'Inguzanyo",
    flowComparison: "Incamake y'Ayinjiye n'Ayasohotse",

    // Settings & Users
    settingsTitle: "Igenamiterere",
    language: "Ururimi rwa Sisitemu",
    languageDesc: "Hitamo hagati y'Icyongereza n'Ikinyarwanda",
    usersRoles: "Abakoresha n'Inshingano",
    usersRolesDesc: "Gena uburenganzira bw'abayobozi",
    manageUsers: "Gena Abakoresha",
    dataBackup: "Ububiko",
    dataBackupDesc: "Bika amakuru yose ya sisitemu",
    exportJson: "Kurura JSON",
    resetDb: "Siba Ububiko",
    resetDbDesc: "Siba byose utangire bushya",
    systemMaintenance: "Kubungabunga Sisitemu",
    clearCache: "Siba Cache",
    clearCacheDesc: "Kemura ibibazo bya sisitemu. Bisaba kwinjira bundi bushya.",
    verifyHealth: "Genzura Ubuzima",
    healthCheckDesc: "Reba niba sisitemu ihujwe neza n'ububiko.",
    systemUsers: "Abakoresha Sisitemu n'Inshingano",
    manageAccess: "Gucunga uburenganzira bw'injira",
    addUser: "Ongeramo Umukoresha",
    totalUsers: "Abakoresha Bose",
    admins: "Abaminisitirateri",
    groupLeaders: "Abayobozi b'Amatsinda",
    lockedDisabled: "Barafunze",
    searchUsers: "Shakisha abakoresha...",
    scope: "Aho akorera",
    lastLogin: "Iheruka kwinjira",
    createUser: "Rema Umukoresha",
    editUser: "Hindura Umukoresha",
    editUserTitle: "Hindura Umukoresha",
    initialPassword: "Ijambo ry'ibanga ry'ibanze",
    assignedGroup: "Itsinda Ayobora",
    saveUser: "Bika Umukoresha",
    removeUser: "Siba Umukoresha",
    never: "Ntabwo arinjira",
    global: "Rusange / Ntabwo",
    enableAi: "Koresha Umufasha (AI)",
    rlsConfig: "Umutekano w'Ububiko (RLS)",
    copySql: "Kopi ya SQL",
    runSqlWarning: "Icyitonderwa: Koresha iyi SQL muri Supabase kugirango wemeze amategeko y'umutekano.",
    clearCacheBtn: "Siba Cache",
    resetLocal: "Sohoka Burundu",
    confirmRemoveUser: "Ese koko urashaka gusiba uyu mukoresha? Iki gikorwa ntikigarurwa.",

    // Audit & Help
    auditLogs: "Raporo y'Ubugenzuzi",
    userGuide: "Imfashanyigisho",
    contactSupport: "Vugisha Ubufasha",
    timestamp: "Igihe",
    userLog: "Umukozi",
    actionLog: "Igikorwa",
    detailsLog: "Ibyakozwe",

    // Layout
    notifications: "Amatangazo",
    markAllRead: "Byose byasomwe",
    noNotifications: "Nta matangazo ahari",
    markRead: "Tandukaho ko yasomwe",
    logout: "Sohoka",
    groupSelector: "Itsinda:",
    switchLanguage: "Hindura Ururimi",
    helpAssistant: "Umufasha",
    askMeAnything: "Mbaza ikijyanye na sisitemu..."
  }
};

export const HELP_CONTENT = {
  en: [
    {
      id: 'getting-started',
      title: 'Getting Started',
      content: 'Welcome to the VJN GSLA System. This system helps you manage Group Savings and Loans Associations efficiently. To begin, select your group from the dropdown in the top header. If you are setting up for the first time, ensure you have created a Group and started a Season.'
    },
    {
      id: 'meeting-mode',
      title: 'Meeting Mode',
      content: 'Use "Start Meeting" when conducting a physical gathering. It allows you to record attendance, savings, loan repayments, and fines for all members in a single flow. Simply mark attendance and enter amounts. Click "Save" at the end to commit all transactions.'
    },
    {
      id: 'shares',
      title: 'Savings & Shares',
      content: 'Shares are the core unit of savings. Each share has a fixed value (e.g., 100 RWF). Members can buy between the minimum and maximum allowed shares per meeting. The system automatically tracks the total value. Avoid editing past share records without a valid reason, as changes are audited.'
    },
    {
      id: 'loans',
      title: 'Loans',
      content: 'Members can request loans up to 3x their savings (configurable). Loans have a duration and interest rate (usually 5% per month). Use the "Loan Calculator" to preview repayment schedules. If a loan is overdue, use the "Penalty Tool" to apply fines.'
    },
    {
      id: 'seasons',
      title: 'Seasons / Cycles',
      content: 'A Season is the operational period of the group (usually 1 year). All financial activities must happen within an open season. At the end, use the "Share-out Report" to calculate dividends based on member savings and group profits.'
    },
    {
      id: 'fines',
      title: 'Fines',
      content: 'Record fines for rule violations (e.g., Late Arrival, Phone usage). You can manage fine categories in the Fines section. System-generated fines (like Absence) can be automated.'
    },
    {
      id: 'expenses',
      title: 'Expense Management',
      content: 'Record any money leaving the group fund (e.g., Stationery, Transport). The system checks against available cash balance before approving. Editing requires a reason and is logged.'
    }
  ],
  rw: [
    {
      id: 'getting-started',
      title: 'Aho uhera',
      content: 'Murakaza neza muri Sisitemu ya VJN GSLA. Iyi sisitemu igufasha gucunga amatsinda yo kuzigama no kugurizanya. Kugirango utangire, hitamo itsinda ryawe hejuru. Niba ari ubwa mbere, banza urebe ko waremye Itsinda kandi ugatangiza Igihembwe.'
    },
    {
      id: 'meeting-mode',
      title: 'Kwandika Inama',
      content: 'Koresha "Inama" igihe muri mu nama y\'itsinda. Igufasha kwandika icyarimwe ubwitabire, imigabane, ubwishyu bw\'inguzanyo, n\'amande ku banyamuryango bose. Hitamo gusa abitabiriye wandike amafaranga batanze. Kanda "Bika" hasi kugirango byose bijye mu bubiko.'
    },
    {
      id: 'shares',
      title: 'Ubwizigame & Imigabane',
      content: 'Imigabane niyo shingiro ry\'ubwizigame. Buri mugabane ufite agaciro kamwe (urugero: 100 RWF). Abanyamuryango bashobora kugura imigabane iri hagati y\'umubare muto n\'umunini wemejwe. Sisitemu ibara agaciro kabyo. Ntugahindure ibyanditswe kera utabifitiye impamvu, kuko biragenzurwa.'
    },
    {
      id: 'loans',
      title: 'Inguzanyo',
      content: 'Umunyamuryango ashobora kugurizwa inshuro 3 z\'ubwizigame bwe (birahindurwa). Inguzanyo zigira igihe n\'inyungu (akenshi 5% ku kwezi). Koresha "Ibalura ry\'Inguzanyo" kureba uko zizishyurwa. Iyo inguzanyo ikererewe, koresha "Gucunga Ibihano" guca amande.'
    },
    {
      id: 'seasons',
      title: 'Ibihembwe',
      content: 'Igihembwe ni igihe itsinda rimara rikola (akenshi umwaka 1). Ibikorwa byose by\'imari bigomba gukorerwa mu gihembwe gifunguye. Iyo kirangiye, koresha "Raporo yo Kugabana" kureba amafaranga buri munyamuryango azahabwa hagendewe ku migabane ye n\'inyungu yabonetse.'
    },
    {
      id: 'fines',
      title: 'Amande',
      content: 'Andika amande y\'abishe amategeko (urugero: Gukererwa, Kuvugira kuri telefoni). Ushobora kurema ibyiciro by\'amande ahanditse Amande. Amande y\'ubwitabire (Gusiba/Gukererwa) ashobora kwikora.'
    },
    {
      id: 'expenses',
      title: 'Gucunga Ayasohotse',
      content: 'Andika amafaranga yose asohoka mu itsinda (urugero: Ibitabo, Tike). Sisitemu ireba niba hari amafaranga ahagije mbere yo kubika. Guhindura bisaba kwerekana impamvu kandi bijya mu bugenzuzi.'
    }
  ]
};
