import React from 'react';
import { 
  LayoutDashboard, Users, BookOpen, Banknote, CalendarCheck, Settings, 
  PieChart, ShieldAlert, Building, Sprout, PiggyBank, Gavel, 
  Receipt, ClipboardCheck, HelpCircle, Bell
} from 'lucide-react';

export const MENU_ITEMS = [
  { id: 'dashboard', label: { en: 'Dashboard', rw: 'Incamake' }, icon: <LayoutDashboard size={20} />, path: '/' },
  { id: 'groups', label: { en: 'Groups', rw: 'Amatsinda' }, icon: <Building size={20} />, path: '/groups' },
  { id: 'members', label: { en: 'Members', rw: 'Abanyamuryango' }, icon: <Users size={20} />, path: '/members' },
  { id: 'seasons', label: { en: 'Seasons / Cycles', rw: 'Igihembwe' }, icon: <Sprout size={20} />, path: '/seasons' },
  { id: 'meeting', label: { en: 'Meeting Mode', rw: 'Inama' }, icon: <BookOpen size={20} />, path: '/meeting' },
  { id: 'contributions', label: { en: 'Contributions', rw: 'Ubwizigame' }, icon: <PiggyBank size={20} />, path: '/contributions' },
  { id: 'loans', label: { en: 'Loans', rw: 'Inguzanyo' }, icon: <Banknote size={20} />, path: '/loans' },
  { id: 'fines', label: { en: 'Fines', rw: 'Amande' }, icon: <Gavel size={20} />, path: '/fines' },
  { id: 'expenses', label: { en: 'Expenses', rw: 'Amafaranga yasohotse' }, icon: <Receipt size={20} />, path: '/expenses' },
  { id: 'attendance', label: { en: 'Attendance', rw: 'Ubwitabire' }, icon: <ClipboardCheck size={20} />, path: '/attendance' },
  { id: 'reports', label: { en: 'Reports', rw: 'Raporo' }, icon: <PieChart size={20} />, path: '/reports' },
  { id: 'notifications', label: { en: 'Announcements', rw: 'Amatangazo' }, icon: <Bell size={20} />, path: '/notifications' },
  { id: 'audit', label: { en: 'Audit Logs', rw: 'Ubugenzuzi' }, icon: <ShieldAlert size={20} />, path: '/audit' },
  { id: 'settings', label: { en: 'Settings', rw: 'Igenamiterere' }, icon: <Settings size={20} />, path: '/settings' },
  { id: 'help', label: { en: 'Help & Support', rw: 'Ubufasha' }, icon: <HelpCircle size={20} />, path: '/help' },
];

export const LABELS = {
  en: {
    welcome: "Welcome back",
    totalSavings: "Total Savings",
    loansActive: "Active Loans",
    members: "Members",
    shareValue: "Share Value",
    currency: "RWF",
    startMeeting: "Start Meeting Recording",
    saveMeeting: "Save Meeting Data",
    present: "Present",
    absent: "Absent",
    late: "Late",
    shares: "Shares",
    repayment: "Repayment",
    fines: "Fines",
    search: "Search...",
    applyLoan: "Apply for Loan",
    status: "Status",
    actions: "Actions",
    approve: "Approve",
    reject: "Reject",
    group: "Group",
    cycle: "Season/Cycle",
    attendance: "Attendance",
    financials: "Financials",
    loading: "Loading...",
    noData: "No records found.",
    date: "Date",
    amount: "Amount",
    description: "Description",
    type: "Type"
  },
  rw: {
    welcome: "Murakaza neza",
    totalSavings: "Ubwizigame Bwose",
    loansActive: "Inguzanyo Zatanzwe",
    members: "Abanyamuryango",
    shareValue: "Agaciro k'Umugabane",
    currency: "RWF",
    startMeeting: "Tangira Kwandika Inama",
    saveMeeting: "Bika Amakuru y'Inama",
    present: "Yitabiriye",
    absent: "Yasibye",
    late: "Yakererewe",
    shares: "Imigabane",
    repayment: "Kwishura",
    fines: "Amande",
    search: "Shakisha...",
    applyLoan: "Saba Inguzanyo",
    status: "Imiterere",
    actions: "Ibikorwa",
    approve: "Emeza",
    reject: "Hakana",
    group: "Itsinda",
    cycle: "Igihembwe",
    attendance: "Ubwitabire",
    financials: "Imari",
    loading: "Birigutunganywa...",
    noData: "Nta makuru ahari.",
    date: "Itariki",
    amount: "Amafaranga",
    description: "Ubusobanuro",
    type: "Ubwoko"
  }
};