
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { User, GSLAGroup, Cycle } from "../types";

// --- Types ---
interface ReportContext {
  reportType: string;
  reportTitle: string;
  group: GSLAGroup;
  user: User | null;
  cycle: Cycle | null;
  data: any;
  filters?: any;
}

// --- Layout Constants ---
const MARGIN = 15;
const HEADER_HEIGHT = 40;
const FOOTER_HEIGHT = 20;
const COLORS = {
  text: [40, 40, 40] as [number, number, number],
  secondary: [100, 100, 100] as [number, number, number],
  accent: [22, 163, 74] as [number, number, number], // Green-600
  headerBg: [240, 240, 240] as [number, number, number],
  alternateRow: [250, 250, 250] as [number, number, number]
};

// --- Helper Functions ---

const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat('en-RW', { style: 'decimal', minimumFractionDigits: 0 }).format(amount) + ' RWF';
};

const prepareTableData = (type: string, data: any) => {
  let head: string[][] = [];
  let body: any[][] = [];
  
  if (!data) return { head, body };

  if (type === 'CASH_FLOW' && data.inflows) {
    head = [['Category', 'Type', 'Amount (RWF)']];
    Object.entries(data.inflows).forEach(([k, v]) => body.push([k, 'Inflow', formatCurrency(v as number)]));
    Object.entries(data.outflows).forEach(([k, v]) => body.push([k, 'Outflow', formatCurrency(v as number)]));
    body.push([{ content: 'Net Cash Position', colSpan: 2, styles: { fontStyle: 'bold', fillColor: [240, 248, 255] } }, { content: formatCurrency(data.netCash), styles: { fontStyle: 'bold', textColor: COLORS.accent } }]);
  } 
  else if (type === 'SHARE_OUT' && data.members) {
    head = [['Member Name', 'Shares', 'Invested', 'Profit', 'Payout']];
    body = data.members.map((m: any) => [
      m.name,
      m.shares,
      formatCurrency(m.invested),
      formatCurrency(m.profit),
      { content: formatCurrency(m.payout || m.currentValue), styles: { fontStyle: 'bold' } }
    ]);
  } 
  else if (Array.isArray(data) && data.length > 0) {
    const firstRow = data[0];
    const keys = Object.keys(firstRow).filter(k => k !== 'id');
    head = [keys.map(k => {
        if (k.includes(' ')) return k;
        return k.replace(/([A-Z])/g, ' $1').trim().replace(/^./, str => str.toUpperCase());
    })];
    body = data.map((row: any) => keys.map(k => {
      const val = row[k];
      if (typeof val === 'number' && (k.toLowerCase().includes('amount') || k.toLowerCase().includes('balance') || k.toLowerCase().includes('savings'))) {
        return formatCurrency(val);
      }
      return val;
    }));
  }

  return { head, body };
};

// --- Main Generator ---

export const generatePDFReport = (context: ReportContext) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  const pageHeight = doc.internal.pageSize.height;
  
  const drawHeader = (data: any) => {
    doc.setFillColor(20, 20, 20);
    doc.rect(MARGIN, 10, 10, 10, 'F'); 
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(8);
    doc.text("VJN", MARGIN + 2, 16);

    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Vision Jeunesse Nouvelle", MARGIN + 15, 17);

    doc.setFontSize(16);
    doc.setTextColor(COLORS.accent[0], COLORS.accent[1], COLORS.accent[2]);
    doc.text(context.reportTitle.toUpperCase(), pageWidth - MARGIN, 17, { align: "right" });

    doc.setDrawColor(200, 200, 200);
    doc.line(MARGIN, 25, pageWidth - MARGIN, 25);
  };

  const drawFooter = (data: any) => {
    const pageNumber = data.pageNumber;
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.line(MARGIN, pageHeight - 15, pageWidth - MARGIN, pageHeight - 15);
    
    doc.text("VJN GSLA Management System", MARGIN, pageHeight - 10);
    doc.text(`Generated on ${new Date().toLocaleString()}`, pageWidth / 2, pageHeight - 10, { align: "center" });
    doc.text(`Page ${pageNumber}`, pageWidth - MARGIN, pageHeight - 10, { align: "right" });
  };

  const drawMetadata = () => {
    doc.setFontSize(10);
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    doc.setFont("helvetica", "normal");

    const metaY = 35;
    const col2X = pageWidth / 2;

    doc.setFont("helvetica", "bold");
    doc.text("Group:", MARGIN, metaY);
    doc.setFont("helvetica", "normal");
    doc.text(context.group.name, MARGIN + 25, metaY);

    doc.setFont("helvetica", "bold");
    doc.text("Season:", MARGIN, metaY + 6);
    doc.setFont("helvetica", "normal");
    doc.text(context.cycle ? `${context.cycle.startDate} - ${context.cycle.endDate || 'Active'}` : 'N/A', MARGIN + 25, metaY + 6);

    doc.setFont("helvetica", "bold");
    doc.text("Generated By:", col2X, metaY);
    doc.setFont("helvetica", "normal");
    doc.text(context.user?.fullName || 'System', col2X + 30, metaY);
  };

  let startY = 55;

  // --- Financial Summary Table (Share-Out Only) ---
  if (context.reportType === 'SHARE_OUT' && context.data.summary?.breakdown) {
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Financial Breakdown", MARGIN, startY);
      
      const b = context.data.summary.breakdown;
      const s = context.data.summary;
      
      const summaryBody = [
          ['Total Share Contributions', formatCurrency(b.contributions)],
          ['Loan Interest Earned', formatCurrency(b.interest)],
          ['Investment Profits', formatCurrency(b.investmentProfits)],
          ['Fines (Share Eligible)', formatCurrency(b.shareEligibleFines)],
          [{ content: 'Total Share-Eligible Income', styles: { fontStyle: 'bold', fillColor: [240, 240, 240] } }, { content: formatCurrency(b.contributions + b.interest + b.investmentProfits + b.shareEligibleFines), styles: { fontStyle: 'bold' } }],
          ['Less: Expenses', `(${formatCurrency(b.expenses)})`],
          ['Less: Investment Losses', `(${formatCurrency(b.investmentLosses)})`],
          [{ content: 'NET DISTRIBUTABLE AMOUNT', styles: { fontStyle: 'bold', textColor: [22, 163, 74] } }, { content: formatCurrency(s.totalDistributable), styles: { fontStyle: 'bold', textColor: [22, 163, 74] } }],
          ['Total Shares', s.members.reduce((a:any,m:any)=>a+m.shares,0)],
          ['VALUE PER SHARE', formatCurrency(s.valuePerShare)]
      ];

      autoTable(doc, {
          startY: startY + 5,
          head: [['Component', 'Amount']],
          body: summaryBody,
          theme: 'grid',
          headStyles: { fillColor: [50, 50, 50], textColor: 255, fontStyle: 'bold' },
          columnStyles: { 1: { halign: 'right' } },
          margin: { left: MARGIN, right: pageWidth / 2 } // Half width
      });

      // Excluded Funds Table (Right Side)
      const excludedBody = [
          ['Social Contributions', formatCurrency(b.socialContributions)],
          ['Social Fines', formatCurrency(b.socialFines)],
          [{ content: 'TOTAL EXCLUDED', styles: { fontStyle: 'bold' } }, { content: formatCurrency(b.socialContributions + b.socialFines), styles: { fontStyle: 'bold' } }]
      ];

      autoTable(doc, {
          startY: startY + 5,
          head: [['Excluded Funds (Non-Share)', 'Amount']],
          body: excludedBody,
          theme: 'grid',
          headStyles: { fillColor: [200, 50, 50], textColor: 255, fontStyle: 'bold' },
          columnStyles: { 1: { halign: 'right' } },
          margin: { left: pageWidth / 2 + 5, right: MARGIN }
      });

      startY = (doc as any).lastAutoTable.finalY + 15;
  }

  const { head, body } = prepareTableData(context.reportType, context.data);

  if (context.reportType === 'SHARE_OUT') {
      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text("Member Payout Schedule", MARGIN, startY - 2);
  }

  autoTable(doc, {
    startY: startY,
    head: head,
    body: body,
    theme: 'grid',
    styles: {
      fontSize: 9,
      cellPadding: 3,
      textColor: COLORS.text,
      lineColor: [220, 220, 220],
      lineWidth: 0.1,
    },
    headStyles: {
      fillColor: COLORS.text,
      textColor: 255,
      fontStyle: 'bold',
      halign: 'center'
    },
    columnStyles: {
        2: { halign: 'right' },
        3: { halign: 'right' },
        4: { halign: 'right' },
        5: { halign: 'right' }
    },
    alternateRowStyles: {
      fillColor: [249, 250, 251]
    },
    margin: { top: HEADER_HEIGHT, bottom: FOOTER_HEIGHT, left: MARGIN, right: MARGIN },
    didDrawPage: (data) => {
      drawHeader(data);
      drawFooter(data);
    },
  });

  // --- Signatures ---
  let finalY = (doc as any).lastAutoTable.finalY + 20;
  
  if (finalY + 40 > pageHeight - FOOTER_HEIGHT) {
      doc.addPage();
      finalY = MARGIN + 20;
  }

  const sigWidth = (pageWidth - (MARGIN * 2)) / 3;
  const sigLineY = finalY + 20;

  doc.setLineWidth(0.5);
  doc.setDrawColor(100, 100, 100);
  doc.setFontSize(9);
  doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);

  doc.line(MARGIN, sigLineY, MARGIN + sigWidth - 10, sigLineY);
  doc.text("Prepared By", MARGIN, sigLineY + 5);

  doc.line(MARGIN + sigWidth, sigLineY, MARGIN + (sigWidth * 2) - 10, sigLineY);
  doc.text("Reviewed By", MARGIN + sigWidth, sigLineY + 5);

  doc.line(MARGIN + (sigWidth * 2), sigLineY, MARGIN + (sigWidth * 3), sigLineY);
  doc.text("Approved By", MARGIN + (sigWidth * 2), sigLineY + 5);

  doc.setPage(1);
  drawMetadata();

  const cleanGroupName = context.group.name.replace(/[^a-z0-9]/gi, '_').toUpperCase();
  const dateStr = new Date().toISOString().slice(0,10).replace(/-/g, '');
  const fileName = `VJN_${cleanGroupName}_${context.reportType}_${dateStr}.pdf`;
  
  doc.save(fileName);
};
